/*
* Constants
*/
export const ACTIONS = {
  RECEIVE_AGENCIES: "RECEIVE_AGENCIES",
  CHANGE_AGENCY_MESSAGE: "CHANGE_AGENCY_MESSAGE",
  CURRENT_AGENCY: "CURRENT_AGENCY",
  RECIEVE_ADVERTISERS: "RECIEVE_ADVERTISERS",
  ADVERTISER_SELECTED: "ADVERTISER_SELECTED",
  CHANGE_ADVERTISERS_MESSAGE: "CHANGE_ADVERTISERS_MESSAGE",
  RECIEVE_CAMPAIGNS: "RECIEVE_CAMPAIGNS",
  CAMPAIGN_NAME_CHANGE: "CAMPAIGN_NAME_CHANGE",
  CAMPAIGN_STATUS_CHANGE: "CAMPAIGN_STATUS_CHANGE",
  CAMPAIGN_BUDGET_CHANGE: "CAMPAIGN_BUDGET_CHANGE",
  CAMPAIGN_START_CHANGE: "CAMPAIGN_START_CHANGE",
  CAMPAIGN_END_CHANGE: "CAMPAIGN_END_CHANGE",
  CAMPAIGN_CHECKBOX_CHANGE: "CAMPAIGN_CHECKBOX_CHANGE",
  SYNC_CAMPAIGN_WITH_API: "SYNC_CAMPAIGN_WITH_API",
  STATUS_MESSAGE: "STATUS_MESSAGE"
}